dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.17
  shimmer: ^3.0.0
  calendar_date_picker2: ^1.1.8
  flutter_slidable: ^4.0.0
  intl: ^0.19.0
  lib_common:
    path: ../lib_common

description: A new Flutter package project that contains the theme for application.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.6.2

flutter:
  assets:
    - assets/svg/
    - assets/json/
  uses-material-design: true
homepage: null
name: lib_style
publish_to: none
version: 0.0.1
