dependencies:
  flutter:
    sdk: flutter
  get_it: 8.0.3
  freezed_annotation: 2.4.4
  json_annotation: ^4.8.1
  intl: ^0.19.0


description: A new Flutter package project that contains the common utility for application.
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
environment:
  sdk: ^3.6.2

flutter:
  uses-material-design: true

homepage: null
name: lib_common
publish_to: none
version: 0.0.1
