dependencies:
  flutter:
    sdk: flutter
  lib_common:
    path: ../lib_common
  lib_style:
    path: ../lib_style
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^6.0.0

description: A new Flutter package project that contains the theme for application.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.6.2

flutter:
  uses-material-design: true
homepage: null
name: lib_employee
publish_to: none
version: 0.0.1
